
 : :NAME HERE : 0 STATE ! ; 
 : :NONAME HERE 1 STATE ! ; 
 : LINK>HASH CELL + ; 
 : LINK>BODY CELL + CELL + ; 
 : HASH HERE :NAME SWAP HEAP ! CELL + @ ; 
 : DJB2 LIT [ 1024 DUP DUP + DUP + + 256 + 4 + 1 + , ] ; 
 : HASHT BL BEGIN KEY OVER OVER = NOT UNTIL DJB2 BEGIN DUP DUP + DUP + DUP + DUP + DUP + + XOR >R KEY OVER OVER = IF TRUE ELSE R> FALSE THEN UNTIL DROP DROP R> ;
 : FINDT LATEST @ BEGIN OVER OVER CELL + @ ISNEGATIVE 1 - AND = IF SWAP DROP TRUE EXIT THEN @ DUP 0 = IF SWAP DROP FALSE EXIT THEN AGAIN ; 
 : ' HASHT FINDT IF CELL + CELL + THEN ;  
 : '= ' ; IMMEDIATE  
 : POSTPONE ' , ; IMMEDIATE 
 
 : >BODY ['] LIT , HERE CELL + , 0 , ;
 : CREATE :NAME ['] LIT , HERE CELL + CELL + CELL + , HERE >BODY !  ['] EXIT , ['] EXIT , LATEST ! ; 
 : DOES> R> >BODY @ ! ; 
 : <BUILDS CREATE 0 , ; 
 
 : VARIABLE CREATE CELL ALLOT ; 
 : CONSTANT CREATE , DOES> @ ; 
 : BUFFER CREATE ALLOT ; 
 : ARRAY CREATE ALLOT DOES> + @ ; 
 : VALUE CREATE , DOES> @ ; 
 : TO ' CELL + @ STATE @ IF ['] LIT , , ['] ! , ELSE ! THEN ; 
 
 : CASE LIT [ 0 , ] ; IMMEDIATE  
 : OF 1 + >R POSTPONE OVER POSTPONE = POSTPONE IF POSTPONE DROP R> ; IMMEDIATE 
 : ENDOF >R POSTPONE ELSE R> ; IMMEDIATE 
 : ENDCASE POSTPONE DROP 0 ?DO POSTPONE THEN LOOP ; IMMEDIATE 
 
 : nCASE 0 >R ; IMMEDIATE  
 : nOF R> 1 + >R ['] OVER , ['] = , ['] ?BRANCH , HERE 0 , ['] DROP ; IMMEDIATE 
 : nENDOF ['] BRANCH , HERE 0 , SWAP DUP HERE SWAP - SWAP !  ; IMMEDIATE
 : nENDCASE ['] DROP  0 ?DO DUP HERE SWAP - SWAP ! LOOP ; IMMEDIATE 
 
 : >BODY CELL + @ ; 
 : DEFER CREATE HERE >BODY ! ['] ABORT , DOES> @ EXECUTE ; 
 : DEFER! >BODY ! ; 
 : IS STATE @ IF POSTPONE ['] POSTPONE DEFER!  ELSE ' DEFER!  THEN ; IMMEDIATE 
 : DEFER@ >BODY @ ; 
 : ACTION-OF STATE @ IF POSTPONE ['] POSTPONE DEFER@ ELSE ' DEFER@ THEN ; IMMEDIATE 

 VARIABLE HANDLER
 0 HANDLER !

 : CATCH SP@ >R HANDLER @ >R RP@ HANDLER !  EXECUTE R> HANDLER !  R> DROP 0 ;
 : THROW ?DUP IF HANDLER @ RP!  R> HANDLER !  R> SWAP >R SP! DROP R> THEN ;
 : ABORT -1 THROW ;
                
 : +FIELD CREATE OVER , + DOES> @ + ;
 : BEGIN-STRUCTURE CREATE HERE 0 0 , DOES> @ ;
 : END-STRUCTURE SWAP ! ;

 : FOR HERE ['] >R , ; IMMEDIATE 
 : NEXT  ['] R> , ['] LIT , -1 , ['] + , ['] DUP , ['] 0# , ['] NOT , ['] ?BRANCH , HERE - , ['] DROP , ; IMMEDIATE 
 : BREAK ['] DUP , ['] R> , ['] LEAVE , ; IMMEDIATE

 : DROPS DROP DROP DROP ; 
 : CFILL FOR OVER OVER ! 1 + NEXT DROPS ;
 : CCOPY FOR OVER @ OVER ! 1 + SWAP 1 + SWAP NEXT DROPS ;
 : TOEND DUP DUP >R >R + SWAP R> + SWAP R> ; 
 : CFILL< FOR OVER OVER ! 1 - NEXT DROPS ;
 : CCOPY< FOR OVER @ OVER ! 1 - SWAP 1 - SWAP NEXT DROPS ;
 : COUNT SWAP OVER BEGIN OVER OVER @ = ;
 : CELLS DUP + DUP + ; \ word is 4 bytes
 : ABS DUP 0< IF NEGATE THEN ;
 : MIN OVER OVER - 0 < IF SWAP THEN DROP ;
 : MAX SWAP MIN ;

 CREATE TIB 80 CHARS ALLOT

 : ACCEPT IF FOR KEY DUP CR <> IF OVER ! 1 + ELSE R> DROP 0 R> THEN NEXT THEN DROP ; 
 
 : HOOK BEGIN >R ;
 : BACK R> AGAIN ;
 : ?BACK R> UNTIL ;


