#---------------------------------------------------------------------
# using pre-processor CPP (GNU GCC)
# for alias register names 
# do not change
# a0, a1, a2, a7 are used by ecalls

# forth struct pointer, constant 
#define usr s10

# instruction pointer, preserved
#define ipt s11

# hash value
#define hsh a0

# link pointer
#define lnk a1

# word pointer
#define wrd a2

# generic
#define fst a3

# generic
#define snd a4

# generic
#define trd a5

# index 
#define idx a6

