 : VOID ;
 : ABORT VOID ;
 : -1 U@ 0# ;
 : 0 -1 -1 NAND ;
 : TRUE -1 ;
 : FALSE 0 ;
 : 1 -1 -1 + -1 NAND ;
 : 2 1 1 + ;
 : 3 2 1 + ;
 : 4 2 2 + ;
 : CELL 4 ;
 : SP U@ ;
 : RP SP CELL + ;
 : LATEST RP CELL + ;
 : HEAP LATEST CELL + ;
 : STATE HEAP CELL + ;
 : SP@ SP @ CELL + ;
 : RP@ RP @ CELL + ;
 : SP! SP ! ;
 : RP! RP ! ;
 : DUP SP@ @ ;
 : NOT DUP NAND ;
 : AND NAND NOT ;
 : - NOT 1 + + ;
 : BRANCH RP@ @ DUP @ + RP@ ! ;
 : ?BRANCH 0# NOT RP@ @ @ CELL - AND RP@ @ + CELL + RP@ ! ;
 : OVER SP@ CELL + @ ;
 : SWAP OVER OVER SP@ CELL + CELL + CELL + ! SP@ CELL + ! ;
 : OR NOT SWAP NOT AND NOT ;
 : NOR OR NOT ;
 : <> - 0# ;
 : = <> NOT ;
 : DROP DUP - + ;
 : NIP SWAP DROP ;
 : TUCK SWAP OVER ;
 : HERE HEAP @ ;
 : ALLOT HERE + HEAP ! ;
 : , HERE ! CELL ALLOT ;
 : +! SWAP OVER @ + SWAP ! ;
 : R> RP@ @ RP@ CELL + RP ! RP@ @ SWAP RP@ ! ;
 : >R RP@ @ SWAP RP@ ! RP@ CELL - RP ! RP@ ! ;
 : R@ R> R> DUP >R SWAP >R ;
 : EXECUTE >R ;
 : COMPILE R> DUP @ , CELL + >R ;
 : LIT RP@ @ DUP CELL + RP@ ! @ ;
 : ['] RP@ @ DUP CELL + RP@ ! @ ;
 : ROT >R SWAP R> SWAP ;
 : -ROT SWAP >R SWAP R> ;
 : XOR OVER OVER AND -ROT NOR NOR ;
 : XNOR XOR NOT ;
 : 0= 0# NOT ;
 : 0< ISNEGATIVE AND 0# ;
 : 2DUP OVER OVER ;
 : 2DROP DROP DROP ;
 : 2SWAP ROT >R ROT R> ;
 : 2@ DUP CELL + @ SWAP @ ;
 : 2! SWAP OVER ! CELL + ! ;
 : 2>R SWAP >R >R ;
 : 2R> R> R> SWAP ;
 : 2R@ R> R> 2DUP >R >R SWAP ;
 : 2* DUP + ;
 : 2** 2* 2* 2* 2* 2* 2* 2* 2* ;
 : 80H 1 2* 2* 2* 2* 2* 2* 2* ;
 : ISNEGATIVE 80H 2** 2** 2** ;
 : IMMEDIATE LATEST @ CELL + DUP @ ISNEGATIVE + SWAP ! ;
 : ] 1 STATE ! ;
 : [ 0 STATE ! ;
 : SP0 LIT [ SP@ , ] ;
 : RP0 LIT [ RP@ , ] ;
 : ISNEGATIVE LIT [ ISNEGATIVE , ] ;
 : IF ['] ?BRANCH , HERE 0 , ;
 : THEN DUP HERE SWAP - SWAP ! ;
 : ELSE ['] BRANCH , HERE 0 , SWAP DUP HERE SWAP - SWAP ! ;
 : BEGIN HERE ;
 : AGAIN ['] BRANCH , HERE - , ;
 : UNTIL ['] ?BRANCH , HERE - , ;
 : WHILE ['] ?BRANCH , HERE 0 , ;
 : REPEAT SWAP ['] BRANCH , HERE - , DUP HERE SWAP - SWAP ! ;
 : DO ['] SWAP , HERE ['] >R , ['] >R , ;
 : LOOP ['] R> , ['] LIT , 1 , ['] + , ['] R> , ['] 2DUP , ['] = , ['] ?BRANCH , HERE - , ['] 2DROP , ;
 : I ['] R@ , ;
 : LEAVE ['] R> , ['] DROP , ['] R> , ['] DROP , ['] EXIT , ;
 : FOR HERE ['] >R , ;
 : NEXT ['] R> , ['] LIT , 1 , ['] - , ['] DUP , ['] 0< , ['] NOT , ['] ?BRANCH , HERE - , ['] DROP , ;
 : ?DUP DUP IF DUP THEN ;
 : CELL LIT [ 4 , ] ;
 : CELLS DUP + DUP + ;
 : 0 LIT [ 0 , ] ;
 : 1 LIT [ 1 , ] ;
 : 2 LIT [ 1 1 + , ] ;
 : 4 LIT [ 2 2 + , ] ;
 : 8 LIT [ 4 4 + , ] ;
 : 16 LIT [ 8 8 + , ] ;
 : 32 LIT [ 16 16 + , ] ;
 : 64 LIT [ 32 32 + , ] ;
 : 128 LIT [ 64 64 + , ] ;
 : BL LIT [ 16 16 + , ] ;
 : QU LIT [ 16 16 + 2 + , ] ;
 : CR 8 2 + EMIT ;
 : NL 8 4 + 1 + EMIT ;
 : SPACE BL EMIT ;
 : SPACES 0 DO SPACE LOOP ;
 : 0> DUP 0= IF DROP FALSE EXIT THEN 0< IF FALSE EXIT THEN TRUE ;
 : 0fh LIT [ 16 1 - , ] ;
 : ffh LIT [ 0fh 2* 2* 2* 2* 0fh OR , ] ;
 : C@ @ ffh AND ;
 : C! DUP @ ffh NOT AND ROT ffh AND OR SWAP ! ;
 : C, HERE C! 1 ALLOT ;
 : ALIGN 3 + TRUE 3 - AND ;
 : TYPE 0 DO DUP C@ EMIT 1 + LOOP DROP ;
 : SKIP BEGIN KEY OVER - 0# UNTIL DROP ;
 : SCAN BEGIN KEY OVER - 0# NOT UNTIL DROP ;
 : \ 8 2 + SCAN ;
 : ( 32 8 + 1 + SCAN ;
 : ." 32 2 + BEGIN KEY OVER OVER - WHILE EMIT REPEAT DROP DROP ;

