\ FIGFORTH

: ' DFIND ZEQU DROP LITER ; IMMEDIATE

: BACK HERE - COMMA ;

: BEGIN HERE ; IMMEDIATE

: IF COMPILE ZBRANCH HERE 0 , ; IMMEDIATE

: ENDIF HERE OVER - SWAP ! ; IMMEDIATE

: ELSE COMPILE BRANCH HERE 0 , SWAP ENDIF ; IMMEDIATE

: THEN ENDIF ; IMMEDIATE

: UNTIL COMPILE ZBRANCH BACK ; IMMEDIATE

: AGAIN COMPILE BRANCH BACK ; IMMEDIATE

: WHILE IF ; IMMEDIATE

: REPEAT AGAIN ENDIF ; IMMEDIATE

: END UNTIL ; IMMEDIATE


