
 \ this file is still a stub 

 ( LOCATORS, BILL RAGSDALE, FIG_FORTH MEET 26/09/2025 )
 ( LINK_LIST, SELECTOR_HASH, PAYLOAD_WHEREVER )

 ( VARIABLE MYLIST 0 MYLIST ! )
 ( MYLIST LINK, 101 , ," MESSAGE 101 " )
 ( MYLIST LINK, 404 , ," MESSAGE 404 " )
 ( MYLIST LINK, 501 , ," MESSAGE 501 " )
 ( MYLIST LINK, 999 , ," MESSAGE 999 " )

 ( VARIABLE DOLIST 0 DOLIST ! )
 ( : EXEC-999 ," EXECUTE IN 999 " )
 ( : EXEC-501 ," EXECUTE IN 501 " )
 ( : EXEC-404 ," EXECUTE IN 404 " )
 ( : EXEC-101 ," EXECUTE IN 101 " )
 ( DOLIST LINK, 999 , ['] EXEC-999 )
 ( DOLIST LINK, 501 , ['] EXEC-501 )
 ( DOLIST LINK, 404 , ['] EXEC-404 )
 ( DOLIST LINK, 101 , ['] EXEC-101 )


 : LINK, HERE OVER @ @ , SWAP ! ;

 : .SEARCH BEGIN @ 2DUP CELL + @ =
        IF SWAP OVER CELL + CELL + TRUE EXIT THEN
        DUP @ 0 = IF DROP DROP FALSE EXIT THEN
        AGAIN ;
 
 : .MESSAGE
        .SEARCH
        IF COUNT TYPE
        ELSE ," NO MESSAGE FOUND "
        THEN ;
 
 : .EXECUTE
        .SEARCH
        IF @ EXECUTE
        ELSE ," NO COMPILED CODE FOUND "
        THEN ;

         
