/*
#---------------------------------------------------------------------
 
  Copyright 2025 Alvaro Gomes Sobral Barcellos <@agsb>
 
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 2 of the License, or
  (at your option) any later version.
 
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.
 
  You should have received a copy of the GNU General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.

#----------------------------------------------------------------------
*/

# ascii

.equ XON, 17   #  ^Q

.equ XOFF, 19  #  ^S

.equ ACK, 6    #  ^F

.equ NAK, 21   #  ^U

.equ BS, 8     # \b ^H

.equ HT, 9     # \t ^I

.equ LF, 10    # \n ^J

.equ VT, 11    # \v ^K

.equ FF, 12    # \f ^L

.equ CR, 13    # \r ^M

.equ CAN, 24   #    ^X

.equ ESC, 27   #    ^[

.equ BL, 32    # blank space

.equ QQ, 34    # quotation marks


