
# DO NOT USE, TOO MANY COLISIONS

# DJB2 hashes with bit 0 cleared, no odd values

.equ hash_EXIT, 0x7C7CC744
.equ hash_COLON, 0x0002B59E
.equ hash_SEMIS, 0x0002B59E
.equ hash_KEY, 0x0B87F112
.equ hash_EMIT, 0x7C7C87D0
.equ hash_STORE, 0x0002B584
.equ hash_FETCH, 0x0002B5E4
.equ hash_NAND, 0x7C8254C0
.equ hash_PLUS, 0x0002B58E
.equ hash_ZEROQ, 0x00596816
.equ hash_USAERAT, 0x005973B0

.equ hash_LSHIFT, 0xAC5784C8
.equ hash_RSHIFT, 0xC16E6B96
.equ hash_DOCODE, 0x075D9A72
.equ hash_ABORT, 0x0C4FFEAE
.equ hash_BYE, 0x0B87C61A
.equ hash_DOT, 0x0002B58A

.equ hash_ALIGN, 0x0C531CC8
.equ hash_TWOMUL, 0x0059685C
.equ hash_TWODIV, 0x00596858
.equ hash_NOT, 0x0B87D3D0
.equ hash_NEG, 0x0B87D488
.equ hash_DUP, 0x0B87BC84
.equ hash_DROP, 0x7C7F5C2C
.equ hash_OVER, 0x7C84398A
.equ hash_SWAP, 0x7C8A3910
.equ hash_ROT, 0x0B8807CC
.equ hash_NROT, 0x7C4E8CA0
.equ hash_CFETCH, 0x005972E6
.equ hash_CSTORE, 0x00597286
.equ hash_MINUS, 0x0002B588
.equ hash_AND, 0x0B87B72E
.equ hash_OR, 0x00597378
.equ hash_XOR, 0x0B883040
.equ hash_EQU, 0x0002B598
.equ hash_LESS, 0x0002B598
.equ hash_RAT, 0x00597496
.equ hash_RTO, 0x005974E8
.equ hash_TOR, 0x005968A8
.equ hash_RPAT, 0x0B880526
.equ hash_RPTO, 0x0B880546
.equ hash_SPAT, 0x0B8811E6
.equ hash_SPTO, 0x0B881186
.equ hash_BRANCH, 0x9E6C4190
.equ hash_ZBRANCH, 0xC865FE00
.equ hash_LIT, 0x0B87DB14
.equ hash_TRUE, 0x7C879BF2
.equ hash_FALSE, 0x0C3C6778
.equ hash_ONE, 0x0002B594
.equ hash_TWO, 0x0002B596
.equ hash_CELL, 0x7C81B0A2
.equ hash_NAN, 0x0B87D404
.equ hash_RPZO, 0x0B880556
.equ hash_SPZO, 0x0B881196
.equ hash_BYMUL, 0x005972C2
.equ hash_BYMOD, 0x7C4D1C6C
.equ hash_PLUSTORE, 0x0059676E

.equ hash_SPLIST, 0x005965D2
.equ hash_RPLIST, 0x005965D2
.equ hash_DUMP, 0x7C7F4FE8
.equ hash_WORDS, 0x0D9A5B98
.equ hash_SEE, 0x0B881316
.equ hash_SHOW, 0x7C8AB346
.equ hash_TDOT, 0x005966C4

