
 \ CANONICAL DJB2 HASH

 : DJB2-CTE ( -- 1505 ) LIT [ 1024 DUP DUP + DUP + + 256 + 4 + 1 + , ] ; 

 : DJB2-HSH ( KEY HSH -- HSH2 ) DUP DUP + DUP + DUP + DUP + DUP + + XOR ;

 : DJB2-VAL 
    BL BEGIN KEY OVER OVER = NOT UNTIL 
    DJB2-CTE >R
    BEGIN 
    R> DJB2-HSH >R
        KEY OVER OVER = 
        IF TRUE ELSE FALSE THEN
    UNTIL
    DROP DROP 
    ( MASK HIGH BIT ) 
    ISNEGATIVE INVERSE R> AND 
    ;

 : HASH DJB2-VAL ; 

